// Render the user-supplied Rhodes Island SVG for the I1 boot/sleep pages.
// Requires Node.js and sharp. Run from any working directory.
const fs = require('node:fs/promises');
const path = require('node:path');
const sharp = require('sharp');

// Keep the existing 256px height, use the wide SVG's natural aspect ratio.
// Width is rounded to a whole I1 byte; the image stays centered in 440px.
const width = 304;
const height = 256;
const source = path.join(__dirname, 'boot_logo_source.svg');
const output = path.resolve(__dirname,
  '../../firmware/frame_film_ark/components/film_ui/src/ui_boot_logo.c');

async function main() {
  // Source is a single cyan path. Convert its paint to black without changing
  // geometry, lettering, holes or margins; the original SVG stays untouched.
  const svg = await fs.readFile(source, 'utf8');
  if (!svg.includes('fill="#18D1FF"')) {
    throw new Error('Expected the supplied cyan Rhodes Island SVG');
  }
  const blackSvg = svg.replace('fill="#18D1FF"', 'fill="#000000"');
  // Rasterize the vector at twice its nominal resolution before reducing it.
  // The small diagonal serif lettering has subpixel strokes at 304px. A
  // midpoint/160 threshold drops them; retain coverage down to ~18% with 210.
  // Keep this deterministic black/white result free of grey dithering.
  const master = await sharp(Buffer.from(blackSvg), { density: 144 })
    .png().toBuffer();
  const base = await sharp(master)
    .resize(width, height, { fit: 'contain', background: '#ffffff' })
    .flatten({ background: '#ffffff' })
    .greyscale().threshold(210).png().toBuffer();
  // Only the two diagonal phrases are re-typeset for the final pixel size.
  // Fixed outlines avoid platform font substitution; white strips cover the
  // original serif text, leaving the tower, base and corner ornaments intact.
  const lettering = await sharp(path.join(__dirname, 'boot_logo_side_text.svg'),
    { density: 576 }).resize(width, height).png().toBuffer();
  // Materialize the composite before thresholding: sharp can otherwise apply
  // threshold before composite and leave grey letters that I1 packing drops.
  const composed = await sharp(base).composite([{ input: lettering }])
    .png().toBuffer();
  const { data: pixels, info } = await sharp(composed)
    .greyscale().threshold(170).raw().toBuffer({ resolveWithObject: true });
  if (info.width !== width || info.height !== height || info.channels !== 1) {
    throw new Error('Unexpected logo raster format');
  }
  await sharp(pixels, { raw: { width, height, channels: 1 } })
    .png().toFile(path.join(__dirname, 'boot_logo_mono.png'));

  // LVGL I1: white index 0, black index 1; BGRA palette then MSB-first pixels.
  const packed = Buffer.alloc(8 + width * height / 8);
  Buffer.from([255, 255, 255, 255, 0, 0, 0, 255]).copy(packed);
  for (let i = 0; i < pixels.length; i++) {
    if (pixels[i] === 0) packed[8 + (i >> 3)] |= 0x80 >> (i & 7);
  }
  const rows = [];
  for (let i = 0; i < packed.length; i += 16) {
    rows.push('    ' + Array.from(packed.subarray(i, i + 16),
      b => '0x' + b.toString(16).padStart(2, '0')).join(', ') + ',');
  }
  await fs.writeFile(output,
    '/* Generated by tools/ui-assets/gen_boot_logo.cjs. */\n' +
    '#include "ui_boot_logo.h"\n\n' +
    `static const uint8_t logo_data[] = {\n${rows.join('\n')}\n};\n\n` +
    'const lv_image_dsc_t ui_boot_logo = {\n' +
    '    .header.magic = LV_IMAGE_HEADER_MAGIC,\n' +
    '    .header.cf = LV_COLOR_FORMAT_I1,\n' +
    `    .header.w = ${width}, .header.h = ${height},\n` +
    `    .header.stride = ${width / 8},\n` +
    '    .data_size = sizeof(logo_data), .data = logo_data,\n};\n');
  console.log(`SVG logo: ${width}x${height}, ${packed.length} bytes`);
}

main().catch(error => { console.error(error.message); process.exitCode = 1; });
