#!/usr/bin/env python3
"""Render two fixed boot headings with locally supplied Novecento Wide fonts.

This generates phrase graphics, not a font or reusable glyph collection.
The source font files are not copied into the repository or firmware.
"""

import argparse
import math
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "firmware/frame_film_ark/components/film_ui/src/ui_boot_typography.c"


def render_phrase(font_path: Path, text: str, size: int, spacing: int) -> Image.Image:
    font = ImageFont.truetype(str(font_path), size)
    image = Image.new("L", (640, 96))
    draw = ImageDraw.Draw(image)
    x = 4.0
    for char in text:
        draw.text((x, 4), char, font=font, fill=255)
        x += font.getlength(char) + spacing
    bounds = image.getbbox()
    if bounds is None:
        raise ValueError("Empty heading")
    image = image.crop(bounds)
    # Slant the rendered phrase artwork, not the font software. Extend the
    # canvas so the upper right edge is not clipped; rasterize only once.
    shear = math.tan(math.radians(12))
    extent = math.ceil(image.height * shear)
    image = image.transform(
        (image.width + extent, image.height), Image.Transform.AFFINE,
        (1, shear, -extent, 0, 1, 0),
        resample=Image.Resampling.BICUBIC,
    )
    if image.width > 440:
        raise ValueError(f"Heading exceeds content width: {image.width}px")
    width = (image.width + 7) // 8 * 8
    packed = Image.new("1", (width, image.height))
    packed.paste(image.point(lambda p: 255 if p >= 96 else 0, mode="1"),
                 ((width - image.width) // 2, 0))
    return packed


def emit(name: str, image: Image.Image) -> str:
    # White index 0, black index 1. Source uses white ink on black canvas.
    data = bytes((255, 255, 255, 255, 0, 0, 0, 255)) + image.tobytes()
    rows = "\n".join(
        "    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ","
        for i in range(0, len(data), 16)
    )
    print(f"{name}: {image.width}x{image.height}, {len(data)} bytes")
    return (
        f"static const uint8_t {name}_data[] = {{\n{rows}\n}};\n"
        f"const lv_image_dsc_t {name} = {{\n"
        "    .header.magic = LV_IMAGE_HEADER_MAGIC,\n"
        "    .header.cf = LV_COLOR_FORMAT_I1,\n"
        f"    .header.w = {image.width}, .header.h = {image.height},\n"
        f"    .header.stride = {image.width // 8},\n"
        f"    .data_size = sizeof({name}_data), .data = {name}_data,\n"
        "};\n\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("font_dir", type=Path)
    args = parser.parse_args()
    title = render_phrase(
        args.font_dir / "Novecentosanswide-DemiBold.otf", "ARKNIGHTS", 48, 6
    )
    subtitle = render_phrase(
        args.font_dir / "Novecentosanswide-Normal.otf",
        "PRTS SYNTHESIZE INFORMATION ANALYSIS OS", 14, 0
    )
    source = (
        "/* Fixed phrase artwork generated by tools/ui-assets/gen_boot_typography.py.\n"
        " * Novecento Sans Wide, Jan Tonellato / Synthview.\n"
        " * No font software or reusable glyph collection is embedded. */\n"
        '#include "ui_boot_typography.h"\n\n'
    )
    source += emit("ui_boot_title", title)
    source += emit("ui_boot_subtitle", subtitle)
    OUT.write_text(source, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
