#!/usr/bin/env python3
"""Convert the supplied dark-background logo to a compact LVGL I1 resource."""

from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[2]
SOURCE = Path(__file__).with_name("boot_logo_source.png")
OUT = ROOT / "firmware/frame_film_ark/components/film_ui/src/ui_boot_logo.c"
SIZE = 256


def main() -> None:
    original = Image.open(SOURCE).convert("L")
    # Preserve the complete composition and original margins; invert the
    # entire source for the user-requested white background.
    # The UI's I1 fast-refresh path has only black and white; diffuse the
    # quantization error to retain the grey PRTS lettering without a coarse
    # repeating ordered grid. Nothing is removed or redrawn.
    logo = ImageOps.invert(original)
    logo.thumbnail((SIZE, SIZE), Image.Resampling.LANCZOS)
    canvas = Image.new("L", (SIZE, SIZE), 255)
    canvas.paste(logo, ((SIZE - logo.width) // 2, (SIZE - logo.height) // 2))
    monochrome = canvas.convert("1", dither=Image.Dither.FLOYDSTEINBERG)
    monochrome.save(SOURCE.with_name("boot_logo_mono.png"))
    # I1 uses MSB-first indexed pixels and an 8-byte BGRA palette.
    data = bytes((255, 255, 255, 255, 0, 0, 0, 255))
    data += bytes(b ^ 0xFF for b in monochrome.tobytes())
    rows = "\n".join(
        "    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ","
        for i in range(0, len(data), 16)
    )
    OUT.write_text(
        '/* Generated by tools/ui-assets/gen_boot_logo.py. */\n'
        '#include "ui_boot_logo.h"\n\n'
        f"static const uint8_t logo_data[] = {{\n{rows}\n}};\n\n"
        "const lv_image_dsc_t ui_boot_logo = {\n"
        "    .header.magic = LV_IMAGE_HEADER_MAGIC,\n"
        "    .header.cf = LV_COLOR_FORMAT_I1,\n"
        f"    .header.w = {SIZE}, .header.h = {SIZE},\n"
        f"    .header.stride = {SIZE // 8},\n"
        "    .data_size = sizeof(logo_data), .data = logo_data,\n"
        "};\n",
        encoding="utf-8", newline="\n",
    )
    print(f"Logo: {SIZE}x{SIZE}, {len(data)} bytes including palette")


if __name__ == "__main__":
    main()
