import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:framefilm_ark/frame_algorithms.dart';
import 'package:framefilm_ark/frame_lut.dart';

void main() {
  test(
    'web convert.js six-colour algorithms agree on a source fixture',
    () async {
      // Expected codes generated by convert.js with the checked-in LUT and
      // Uint8ClampedArray, contrast=1.2, saturation=1.1, strength=1.3.
      const source = <List<int>>[
        [20, 60, 180],
        [40, 170, 220],
        [250, 240, 15],
        [95, 85, 80],
        [120, 190, 25],
        [180, 40, 35],
        [230, 230, 230],
        [70, 70, 70],
        [15, 120, 85],
        [150, 30, 190],
        [210, 160, 50],
        [25, 25, 25],
      ];
      final cases = <(FrameAlgorithm, List<int>)>[
        (FrameAlgorithm.atkinsonEnhanced, [4, 1, 2, 0, 2, 3, 1, 0, 5, 4, 2, 0]),
        (FrameAlgorithm.floydSteinberg, [4, 1, 2, 0, 5, 3, 1, 0, 5, 4, 2, 0]),
        (FrameAlgorithm.atkinson, [4, 1, 2, 0, 5, 3, 1, 0, 5, 4, 2, 0]),
        (FrameAlgorithm.stucki, [4, 1, 2, 0, 5, 3, 1, 0, 5, 4, 2, 0]),
        (FrameAlgorithm.jarvis, [4, 1, 2, 0, 5, 3, 1, 0, 5, 4, 2, 0]),
        (
          FrameAlgorithm.gammaFloydSteinberg,
          [4, 1, 2, 0, 5, 0, 1, 0, 5, 4, 3, 0],
        ),
        (FrameAlgorithm.bayer, [4, 4, 2, 0, 2, 3, 1, 0, 5, 4, 2, 0]),
      ];
      final correction = forFilmCorrectionLut;
      final selection = forFilmSelectionLut;
      for (final (algorithm, expected) in cases) {
        final pixels = Uint8List.fromList([
          for (final rgb in source) ...[...rgb, 255],
        ]);
        adjustFrameColors(pixels, contrast: 1.2, saturation: 1.1);
        final codes = await quantizeFramePixels(
          pixels,
          4,
          3,
          algorithm: algorithm,
          strength: 1.3,
          correctionLut: correction,
          selectionLut: selection,
        );
        expect(codes, expected, reason: algorithm.name);
        for (var i = 0; i < codes.length; i++) {
          expect(pixels.sublist(i * 4, i * 4 + 3), filmPalette[codes[i]]);
        }
      }
    },
  );

  test('dither disabled follows web nearest-colour packing path', () async {
    final pixels = Uint8List.fromList([40, 170, 220, 255]);
    final codes = await quantizeFramePixels(
      pixels,
      1,
      1,
      algorithm: FrameAlgorithm.atkinsonEnhanced,
      dither: false,
    );
    expect(codes, [1]);
  });
}
