#!/usr/bin/env python3
"""Generate compact, 1-bpp LVGL fonts from Ark UI string literals.

Uses the Source Han Sans SC font and OFL license bundled with Ark's LVGL.
Run from any directory with Python 3.10+ and Pillow installed.
"""

import argparse
import re
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[2]
ARK = ROOT / "firmware/frame_film_ark"
FONT_ROOT = ARK / "managed_components/lvgl__lvgl/scripts/generators/built_in_font"
SOURCE = FONT_ROOT / "SourceHanSansSC-Normal.otf"
OUT = ARK / "components/film_ui/src/ui_fonts.c"
SIZES = (14, 18, 24, 36)
# Large fonts only serve these headings. Keep their explicit glyph set small:
# Ark has two 1900-KiB OTA slots; duplicating every small-text glyph wastes flash.
LARGE_TEXT = {
    24: "图片通行证模板时钟动图设置IMAGEPASSTEMPLATECLOCKANIMATIONSETTINGS",
    36: "通行证已休眠PASSSTANDBY",
}


def characters() -> list[str]:
    """Include printable ASCII plus non-ASCII literals in actual UI sources."""
    chars = set(map(chr, range(32, 127)))
    files = list((ARK / "components/film_app/pages").glob("*.c"))
    files += [ARK / "components/film_app/core/app_shell.c"]
    files += list((ARK / "components/film_app/apps").glob("*/app_*.c"))
    token = re.compile(r'"(?:\\.|[^"\\])*"|//[^\n]*|/\*.*?\*/', re.S)
    for path in files:
        for match in token.finditer(path.read_text(encoding="utf-8")):
            literal = match.group()
            if literal.startswith('"'):
                chars.update(c for c in literal if 127 < ord(c) < 65536)
    return sorted(chars, key=ord)


def emit_font(size: int, chars: list[str]) -> tuple[str, int]:
    font = ImageFont.truetype(str(SOURCE), size)
    bitmap = bytearray()
    descriptors = ["    {0},"]
    for char in chars:
        x0, y0, x1, y1 = font.getbbox(char, anchor="ls")
        width, height = x1 - x0, y1 - y0
        image = Image.new("L", (max(1, width), max(1, height)))
        ImageDraw.Draw(image).text(
            (-x0, -y0), char, font=font, fill=255, anchor="ls"
        )
        packed = bytearray((width * height + 7) // 8)
        for index, value in enumerate(image.tobytes()[: width * height]):
            if value >= 96:
                packed[index // 8] |= 0x80 >> (index % 8)
        descriptors.append(
            "    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, "
            ".box_h = %d, .ofs_x = %d, .ofs_y = %d}, /* U+%04X */"
            % (len(bitmap), round(font.getlength(char) * 16), width,
               height, x0, -y1, ord(char))
        )
        bitmap.extend(packed)
    prefix = f"font_{size}"
    rows = [
        "    " + ", ".join(f"0x{v:02x}" for v in bitmap[i:i + 16]) + ","
        for i in range(0, len(bitmap), 16)
    ]
    offsets = ", ".join(str(ord(c) - 32) for c in chars)
    result = f"""
static const uint8_t {prefix}_bitmap[] = {{
{chr(10).join(rows)}
}};
static const lv_font_fmt_txt_glyph_dsc_t {prefix}_glyphs[] = {{
{chr(10).join(descriptors)}
}};
static const uint16_t {prefix}_unicodes[] = {{{offsets}}};
static const lv_font_fmt_txt_cmap_t {prefix}_cmap[] = {{{{
    .range_start = 32, .range_length = {ord(chars[-1]) - 31},
    .glyph_id_start = 1, .unicode_list = {prefix}_unicodes,
    .list_length = {len(chars)}, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
}}}};
static const lv_font_fmt_txt_dsc_t {prefix}_dsc = {{
    .glyph_bitmap = {prefix}_bitmap, .glyph_dsc = {prefix}_glyphs,
    .cmaps = {prefix}_cmap, .cmap_num = 1, .bpp = 1,
    .bitmap_format = LV_FONT_FMT_TXT_PLAIN, .stride = 0
}};
const lv_font_t ui_font_{size} = {{
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = {size + 4}, .base_line = 4,
    .cap_height = {size}, .x_height = {size * 2 // 3},
    .subpx = LV_FONT_SUBPX_NONE, .kerning = LV_FONT_KERNING_NONE,
    .static_bitmap = 1, .underline_position = -2,
    .underline_thickness = 1, .dsc = &{prefix}_dsc
}};
"""
    return result, len(bitmap)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check generated output")
    args = parser.parse_args()
    chars = characters()
    output = (
        "/* Generated by tools/ark-font/gen_fonts.py; do not edit.\n"
        " * Ark UI subset derived from Source Han Sans SC (SIL OFL 1.1).\n"
        " * License: tools/ark-font/OFL.txt; 1-bpp, continuous packed rows. */\n"
        '#include "ui_fonts.h"\n'
    )
    for size in SIZES:
        size_chars = sorted(set(LARGE_TEXT[size]), key=ord) if size in LARGE_TEXT else chars
        source, count = emit_font(size, size_chars)
        output += source
        print(f"{size}px: {len(size_chars)} glyphs, {count} bitmap bytes")
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != output:
            raise SystemExit("UI font is stale; run gen_fonts.py")
    else:
        OUT.write_text(output, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
