// Port the frozen upstream numeric pipeline to pure Dart. No JS runtime is used.
const fs=require('fs'),vm=require('vm'),mod={exports:{}};
vm.runInNewContext(process.binding('natives')['internal/deps/acorn/acorn/dist/acorn'],{module:mod,exports:mod.exports});
const ast=mod.exports.parse(fs.readFileSync('tools/ForFilm/js/sz_enhanced.js','utf8'),{ecmaVersion:2020});
const body=ast.body[0].expression.callee.body.body;
const asyncNames=new Set(['balancedToneMap','boxBlur','sobelMagnitude','detectFilmStrips','v5SeedDither','quantize','szEnhancedDither','dilateMask']);
let asyncContext=false,depth=0;
function truth(n) {
 const bool = n.type==='LogicalExpression' || n.type==='UnaryExpression'&&n.operator==='!' || n.type==='Literal'&&typeof n.value==='boolean' || n.type==='BinaryExpression'&&['===','!==','==','!=','<','>','<=','>='].includes(n.operator);
 return bool ? expr(n) : '_truth('+expr(n)+')';
}
function expr(n){if(!n)return '';switch(n.type){
case 'Identifier':return n.name==='Infinity'?'double.infinity':n.name;
case 'Literal':return n.value===null?'null':JSON.stringify(n.value);
case 'ArrayExpression':return '<dynamic>['+n.elements.map(expr).join(',')+']';
case 'ObjectExpression':return '<String,dynamic>{'+n.properties.map(p=>JSON.stringify(p.key.name||p.key.value)+':'+expr(p.value)).join(',')+'}';
case 'BinaryExpression':return '('+expr(n.left)+' '+({'===':'==','!==':'!='}[n.operator]||n.operator)+' '+expr(n.right)+')';
case 'LogicalExpression':return '('+truth(n.left)+' '+n.operator+' '+truth(n.right)+')';
case 'UnaryExpression':return n.operator==='!'?'(!'+truth(n.argument)+')':'('+n.operator+expr(n.argument)+')';
case 'ConditionalExpression':return '('+truth(n.test)+' ? '+expr(n.consequent)+' : '+expr(n.alternate)+')';
case 'MemberExpression':if(n.object.name==='Math'&&n.property.name==='PI')return 'math.pi';if(!n.computed&&n.property.name==='length')return expr(n.object)+'.length';return expr(n.object)+'['+(n.computed?expr(n.property):JSON.stringify(n.property.name))+']';
case 'AssignmentExpression':return expr(n.left)+' '+n.operator+' '+expr(n.right);
case 'UpdateExpression':return n.prefix?n.operator+expr(n.argument):expr(n.argument)+n.operator;
case 'NewExpression':if(n.callee.name==='ImageData')return '_image('+n.arguments.map(expr).join(',')+')';return '_array('+JSON.stringify(n.callee.name)+','+n.arguments.map(expr).join(',')+')';
case 'CallExpression':{
let name,args=n.arguments.map(expr).join(',');
if(n.callee.type==='MemberExpression'){
const p=n.callee.property.name,o=expr(n.callee.object);
if(n.callee.object.name==='Math')return '_math'+p+'('+args+')';
if(['set','fill','slice','push'].includes(p))return '_'+p+'('+o+(args?','+args:'')+')';
name=expr(n.callee);
}else name=expr(n.callee);
return (asyncNames.has(name)?'await ':'')+name+'('+args+')';}
case 'FunctionExpression':return fn(n,false);
default:throw new Error(n.type);
}}
function fn(n,named){const old=asyncContext,oldDepth=depth;asyncContext=named&&asyncNames.has(n.id.name);depth=0;const out=(named?(asyncContext?'Future<dynamic> ':'dynamic ')+n.id.name:'')+'('+n.params.map(p=>'dynamic '+p.name).join(',')+')'+(asyncContext?' async ':' ')+stmt(n.body);asyncContext=old;depth=oldDepth;return out;}
function decl(n){return 'dynamic '+n.declarations.map(d=>expr(d.id)+(d.init?' = '+expr(d.init):'')).join(', ');}
function stmt(n){switch(n.type){
case 'FunctionDeclaration':return fn(n,true)+'\n';
case 'VariableDeclaration':return decl(n)+';\n';
case 'ExpressionStatement':return expr(n.expression)+';\n';
case 'BlockStatement':return '{\n'+n.body.map(stmt).join('')+'}\n';
case 'ReturnStatement':return 'return '+expr(n.argument)+';\n';
case 'IfStatement':return 'if ('+truth(n.test)+') '+stmt(n.consequent)+(n.alternate?'else '+stmt(n.alternate):'');
case 'ForStatement':{const loopName=n.init?.declarations?.[0]?.id?.name || '';const coop=asyncContext&&(depth===0 || /^y\d*$|^rowStep$/.test(loopName));depth++;let b=stmt(n.body);depth--;if(coop){if(n.body.type!=='BlockStatement')b='{\n'+b+'}\n';b=b.replace('{\n','{\nif ((++_ticks & 31) == 0 && _shouldYield()) await _yield();\n');}return 'for ('+(n.init?.type==='VariableDeclaration'?decl(n.init):expr(n.init))+'; '+(n.test?truth(n.test):'')+'; '+expr(n.update)+') '+b;}
case 'WhileStatement':return 'while ('+truth(n.test)+') '+stmt(n.body);
case 'ContinueStatement':return 'continue;\n';case 'BreakStatement':return 'break;\n';
case 'SwitchStatement':return 'switch ('+expr(n.discriminant)+') {\n'+n.cases.map(c=>(c.test?'case '+expr(c.test):'default')+':\n'+c.consequent.map(stmt).join('')).join('')+'}\n';
default:throw new Error(n.type);
}}
let out="// Generated by tool/sync_forfilm_sz.cjs from tools/ForFilm/js/sz_enhanced.js.\n// Pure Dart numerical port; upstream names retained for review and comparison.\n// ignore_for_file: non_constant_identifier_names, prefer_final_locals, avoid_dynamic_calls, unnecessary_parenthesis, prefer_function_declarations_over_variables, curly_braces_in_flow_control_structures\nimport 'dart:collection';\nimport 'dart:math' as math;\nimport 'dart:typed_data';\n\n";
out+=fs.readFileSync('flutter_app/tool/sz_dart_prelude.txt','utf8');out+='\nclass _SzEngine {\nfinal void Function()? checkCancelled;\nfinal void Function(double)? onProgress;\n_SzEngine(this.checkCancelled,this.onProgress);\nint _ticks = 0;\nfinal Stopwatch _sliceWatch = Stopwatch()..start();\n// Schedule a browser timer only after useful work, not every32 pixels.\nbool _shouldYield() {checkCancelled?.call();return _sliceWatch.elapsedMilliseconds >= 8;}\nFuture<void> _yield() async {checkCancelled?.call();await Future<void>.delayed(Duration.zero);_sliceWatch.reset();checkCancelled?.call();}\n';
for(const n of body){if(n.type==='ExpressionStatement')continue;out+=stmt(n);}
out+='}\n';
for(const [marker,progress] of [
 ['dynamic seedLabels = await v5SeedDither(imageData);',.15],
 ['dynamic tone = await balancedToneMap(imageData);',.3],
 ['dynamic grad = await sobelMagnitude(await boxBlur(lightness,width,height,1),width,height);',.4],
 ['dynamic filmStrips = await detectFilmStrips(tone["toneL"],width,height,panelBlack);',.45],
 ['dynamic v7Labels = await quantize(tone,grad,filmStrips,v7Config(),perceived,seedLabels);',.65],
 ['dynamic v75Labels = await quantize(tone,grad,filmStrips,v75Config(),perceived,v7Labels);',.85],
]) out=out.replace(marker,marker+'\nonProgress?.call('+progress+');checkCancelled?.call();');
fs.writeFileSync('flutter_app/lib/frame_sz.dart',out);
