// Generated by tool/sync_forfilm_sz.cjs from tools/ForFilm/js/sz_enhanced.js.
// Pure Dart numerical port; upstream names retained for review and comparison.
// ignore_for_file: non_constant_identifier_names, prefer_final_locals, avoid_dynamic_calls, unnecessary_parenthesis, prefer_function_declarations_over_variables, curly_braces_in_flow_control_structures
import 'dart:collection';
import 'dart:math' as math;
import 'dart:typed_data';

// JS typed-array stores coerce numbers; Float64Array also accepts integer values.
class _NumericArray extends ListBase<dynamic> {
  _NumericArray(this.kind, dynamic lengthOrData)
    : values = lengthOrData is num
          ? List<num>.filled(lengthOrData.toInt(), 0)
          : List<num>.from(lengthOrData as Iterable);
  final String kind;
  final List<num> values;
  @override
  int get length => values.length;
  @override
  set length(int n) => values.length = n;
  @override
  dynamic operator [](int i) => values[i];
  @override
  void operator []=(int i, dynamic v) {
    final n = v as num;
    if (kind == 'Uint8ClampedArray') {
      final f = n.toDouble().clamp(0, 255), low = f.floor(), part = f - low;
      values[i] = part > .5 || (part == .5 && low.isOdd) ? low + 1 : low;
    } else if (kind == 'Uint8Array') {
      values[i] = n.toInt() & 255;
    } else {
      values[i] = n.toDouble();
    }
  }
}

dynamic _array(String kind, dynamic size) => _NumericArray(kind, size);
bool _truth(dynamic value) => value != null && value != false && value != 0;
dynamic _image(dynamic width, dynamic height) => <String, dynamic>{
  'width': width,
  'height': height,
  'data': _NumericArray('Uint8ClampedArray', width * height * 4),
};
dynamic _set(dynamic target, dynamic source) {
  for (var i = 0; i < source.length; i++) {
    target[i] = source[i];
  }
  return target;
}

dynamic _push(dynamic target, dynamic value) {
  target.add(value);
  return target.length;
}

dynamic _mathpow(dynamic x, dynamic p) => math.pow(x as num, p as num);
dynamic _mathmin(dynamic x, dynamic y) => math.min(x as num, y as num);
dynamic _mathmax(dynamic x, dynamic y) => math.max(x as num, y as num);
dynamic _mathsqrt(dynamic x) => math.sqrt(x as num);
dynamic _mathcbrt(dynamic x) =>
    (x as num) < 0 ? -math.pow(-x, 1 / 3) : math.pow(x, 1 / 3);
dynamic _mathabs(dynamic x) => (x as num).abs();
dynamic _mathfloor(dynamic x) => (x as num).floor();
dynamic _mathceil(dynamic x) => (x as num).ceil();
dynamic _mathround(dynamic x) => ((x as num) + .5).floor();
dynamic _mathexp(dynamic x) => math.exp(x as num);
dynamic _mathhypot(dynamic x, dynamic y) => math.sqrt(x * x + y * y);
dynamic _mathatan2(dynamic y, dynamic x) => math.atan2(y as num, x as num);
dynamic _mathcos(dynamic x) => math.cos(x as num);
dynamic _mathsin(dynamic x) => math.sin(x as num);

/// Frozen YRD0370 V7.5 seed, structure refinement and sparkle/chroma cleanup.
Future<Uint8List> quantizeSz(
  Uint8List rgba,
  int width,
  int height, {
  void Function()? checkCancelled,
  void Function(double)? onProgress,
}) async {
  checkCancelled?.call();
  final engine = _SzEngine(checkCancelled, onProgress);
  final input = <String, dynamic>{
    'width': width,
    'height': height,
    'data': rgba,
  };
  final output = await engine.szEnhancedDither(input);
  final data = output['data'];
  const display = [
    [0, 0, 0],
    [255, 255, 255],
    [255, 255, 0],
    [255, 0, 0],
    [0, 255, 0],
    [0, 0, 255],
  ];
  const toFilm = [0, 1, 2, 3, 5, 4];
  final indices = Uint8List(width * height);
  for (var i = 0; i < indices.length; i++) {
    final p = i * 4;
    final index = display.indexWhere(
      (c) => c[0] == data[p] && c[1] == data[p + 1] && c[2] == data[p + 2],
    );
    indices[i] = toFilm[index];
    rgba[p] = data[p];
    rgba[p + 1] = data[p + 1];
    rgba[p + 2] = index == 4 ? 20 : data[p + 2];
    if (index == 4) {
      rgba[p] = 41;
      rgba[p + 1] = 204;
    }
    rgba[p + 3] = 255;
  }
  checkCancelled?.call();
  onProgress?.call(.9);
  return indices;
}

class _SzEngine {
  final void Function()? checkCancelled;
  final void Function(double)? onProgress;
  _SzEngine(this.checkCancelled, this.onProgress);
  int _ticks = 0;
  final Stopwatch _sliceWatch = Stopwatch()..start();
  // Schedule a browser timer only after useful work, not every32 pixels.
  bool _shouldYield() {
    checkCancelled?.call();
    return _sliceWatch.elapsedMilliseconds >= 8;
  }

  Future<void> _yield() async {
    checkCancelled?.call();
    await Future<void>.delayed(Duration.zero);
    _sliceWatch.reset();
    checkCancelled?.call();
  }

  dynamic PALETTE_OUTPUT = <dynamic>[
    <dynamic>[0, 0, 0],
    <dynamic>[255, 255, 255],
    <dynamic>[255, 255, 0],
    <dynamic>[255, 0, 0],
    <dynamic>[0, 255, 0],
    <dynamic>[0, 0, 255],
  ];
  dynamic PALETTE_PERCEIVED = <dynamic>[
    <dynamic>[2, 2, 2],
    <dynamic>[190, 200, 200],
    <dynamic>[197.477795, 194.494739, 6.653345],
    <dynamic>[88.942443, 10.069738, 5.819193],
    <dynamic>[35.987383, 74.688839, 23.922108],
    <dynamic>[0, 18.061406, 148.165358],
  ];
  dynamic UPSTREAM_PERCEIVED = <dynamic>[
    <dynamic>[2, 2, 2],
    <dynamic>[190, 200, 200],
    <dynamic>[197.477795, 194.494739, 6.653345],
    <dynamic>[88.942443, 10.069738, 5.819193],
    <dynamic>[0, 0, 0],
    <dynamic>[0, 18.061406, 148.165358],
    <dynamic>[35.987383, 74.688839, 23.922108],
  ];
  dynamic UPSTREAM_TO_LABEL = <dynamic>[0, 1, 2, 3, 0, 5, 4];
  dynamic BAYER8 = <dynamic>[
    0,
    48,
    12,
    60,
    3,
    51,
    15,
    63,
    32,
    16,
    44,
    28,
    35,
    19,
    47,
    31,
    8,
    56,
    4,
    52,
    11,
    59,
    7,
    55,
    40,
    24,
    36,
    20,
    43,
    27,
    39,
    23,
    2,
    50,
    14,
    62,
    1,
    49,
    13,
    61,
    34,
    18,
    46,
    30,
    33,
    17,
    45,
    29,
    10,
    58,
    6,
    54,
    9,
    57,
    5,
    53,
    42,
    26,
    38,
    22,
    41,
    25,
    37,
    21,
  ];
  dynamic FS_TAPS = <dynamic>[
    <dynamic>[1, 0, (7 / 16)],
    <dynamic>[(-1), 1, (3 / 16)],
    <dynamic>[0, 1, (5 / 16)],
    <dynamic>[1, 1, (1 / 16)],
  ];
  dynamic PI = math.pi;
  dynamic clamp(dynamic v, dynamic low, dynamic high) {
    return ((v < low) ? low : ((v > high) ? high : v));
  }

  dynamic smoothstep(dynamic low, dynamic high, dynamic value) {
    if ((high <= low)) {
      return ((value >= high) ? 1 : 0);
    }
    dynamic t = clamp(((value - low) / (high - low)), 0, 1);
    return ((t * t) * (3 - (2 * t)));
  }

  dynamic srgbToLinearChannel(dynamic encoded) {
    dynamic value = clamp((encoded / 255), 0, 1);
    return ((value <= 0.04045)
        ? (value / 12.92)
        : _mathpow(((value + 0.055) / 1.055), 2.4));
  }

  dynamic linearToSrgbChannel(dynamic linear) {
    linear = clamp(linear, 0, 1);
    dynamic encoded = ((linear <= 0.0031308)
        ? (12.92 * linear)
        : ((1.055 * _mathpow(linear, (1 / 2.4))) - 0.055));
    return (encoded * 255);
  }

  dynamic rgbToOklab(dynamic r, dynamic g, dynamic b) {
    dynamic rl = srgbToLinearChannel(r);
    dynamic gl = srgbToLinearChannel(g);
    dynamic bl = srgbToLinearChannel(b);
    dynamic l =
        (((0.4122214708 * rl) + (0.5363325363 * gl)) + (0.0514459929 * bl));
    dynamic m =
        (((0.2119034982 * rl) + (0.6806995451 * gl)) + (0.1073969566 * bl));
    dynamic s =
        (((0.0883024619 * rl) + (0.2817188376 * gl)) + (0.6299787005 * bl));
    dynamic lr = _mathcbrt(l);
    dynamic mr = _mathcbrt(m);
    dynamic sr = _mathcbrt(s);
    return <dynamic>[
      (((0.2104542553 * lr) + (0.793617785 * mr)) - (0.0040720468 * sr)),
      (((1.9779984951 * lr) - (2.428592205 * mr)) + (0.4505937099 * sr)),
      (((0.0259040371 * lr) + (0.7827717662 * mr)) - (0.808675766 * sr)),
    ];
  }

  dynamic oklabToRgb(dynamic lab) {
    dynamic ll = ((lab[0] + (0.3963377774 * lab[1])) + (0.2158037573 * lab[2]));
    dynamic mm = ((lab[0] - (0.1055613458 * lab[1])) - (0.0638541728 * lab[2]));
    dynamic ss = ((lab[0] - (0.0894841775 * lab[1])) - (1.291485548 * lab[2]));
    dynamic l = ((ll * ll) * ll);
    dynamic m = ((mm * mm) * mm);
    dynamic s = ((ss * ss) * ss);
    return <dynamic>[
      linearToSrgbChannel(
        (((4.0767416621 * l) - (3.3077115913 * m)) + (0.2309699292 * s)),
      ),
      linearToSrgbChannel(
        ((((-1.2684380046) * l) + (2.6097574011 * m)) - (0.3413193965 * s)),
      ),
      linearToSrgbChannel(
        ((((-0.0041960863) * l) - (0.7034186147 * m)) + (1.707614701 * s)),
      ),
    ];
  }

  dynamic LAB_EPSILON = (216 / 24389);
  dynamic LAB_KAPPA = (24389 / 27);
  dynamic labForward(dynamic value) {
    return ((value > LAB_EPSILON)
        ? _mathcbrt(value)
        : (((LAB_KAPPA * value) + 16) / 116));
  }

  dynamic labInverse(dynamic value) {
    dynamic cube = ((value * value) * value);
    return ((cube > LAB_EPSILON) ? cube : (((116 * value) - 16) / LAB_KAPPA));
  }

  dynamic rgbToCielab(dynamic r, dynamic g, dynamic b) {
    dynamic rl = srgbToLinearChannel(r);
    dynamic gl = srgbToLinearChannel(g);
    dynamic bl = srgbToLinearChannel(b);
    dynamic x =
        ((((0.4124564 * rl) + (0.3575761 * gl)) + (0.1804375 * bl)) / 0.95047);
    dynamic y = (((0.2126729 * rl) + (0.7151522 * gl)) + (0.072175 * bl));
    dynamic z =
        ((((0.0193339 * rl) + (0.119192 * gl)) + (0.9503041 * bl)) / 1.08883);
    dynamic fx = labForward(x);
    dynamic fy = labForward(y);
    dynamic fz = labForward(z);
    return <dynamic>[((116 * fy) - 16), (500 * (fx - fy)), (200 * (fy - fz))];
  }

  dynamic cielabToRgb(dynamic lab) {
    dynamic fy = ((lab[0] + 16) / 116);
    dynamic fx = (fy + (lab[1] / 500));
    dynamic fz = (fy - (lab[2] / 200));
    dynamic x = (0.95047 * labInverse(fx));
    dynamic y = labInverse(fy);
    dynamic z = (1.08883 * labInverse(fz));
    dynamic r = (((3.2404542 * x) - (1.5371385 * y)) - (0.4985314 * z));
    dynamic g = ((((-0.969266) * x) + (1.8760108 * y)) + (0.041556 * z));
    dynamic b = (((0.0556434 * x) - (0.2040259 * y)) + (1.0572252 * z));
    return <dynamic>[
      linearToSrgbChannel(r),
      linearToSrgbChannel(g),
      linearToSrgbChannel(b),
    ];
  }

  dynamic oklabAdd(dynamic f, dynamic s) {
    return <dynamic>[(f[0] + s[0]), (f[1] + s[1]), (f[2] + s[2])];
  }

  dynamic oklabMultiply(dynamic v, dynamic scalar) {
    return <dynamic>[(v[0] * scalar), (v[1] * scalar), (v[2] * scalar)];
  }

  dynamic oklabMix(dynamic f, dynamic s, dynamic secondWeight) {
    return oklabAdd(
      oklabMultiply(f, (1 - secondWeight)),
      oklabMultiply(s, secondWeight),
    );
  }

  dynamic squaredDistance(dynamic f, dynamic s) {
    dynamic dl = (f[0] - s[0]);
    dynamic da = (f[1] - s[1]);
    dynamic db = (f[2] - s[2]);
    return ((((1.18 * dl) * dl) + (da * da)) + (db * db));
  }

  dynamic squaredRgbDistance(dynamic f, dynamic s) {
    dynamic dr = (f[0] - s[0]);
    dynamic dg = (f[1] - s[1]);
    dynamic db = (f[2] - s[2]);
    return ((((dr * dr) + (dg * dg)) + (db * db)) / ((3 * 255) * 255));
  }

  dynamic chroma(dynamic lab) {
    return _mathhypot(lab[1], lab[2]);
  }

  dynamic upstreamRgbToLab(dynamic r, dynamic g, dynamic b) {
    r = (r / 255);
    g = (g / 255);
    b = (b / 255);
    r = ((r > 0.04045) ? _mathpow(((r + 0.055) / 1.055), 2.4) : (r / 12.92));
    g = ((g > 0.04045) ? _mathpow(((g + 0.055) / 1.055), 2.4) : (g / 12.92));
    b = ((b > 0.04045) ? _mathpow(((b + 0.055) / 1.055), 2.4) : (b / 12.92));
    dynamic x = ((((r * 0.4124564) + (g * 0.3575761)) + (b * 0.1804375)) * 100);
    dynamic y = ((((r * 0.2126729) + (g * 0.7151522)) + (b * 0.072175)) * 100);
    dynamic z = ((((r * 0.0193339) + (g * 0.119192)) + (b * 0.9503041)) * 100);
    x = (x / 95.047);
    y = (y / 100);
    z = (z / 108.883);
    x = ((x > 0.008856) ? _mathpow(x, (1 / 3)) : ((7.787 * x) + (16 / 116)));
    y = ((y > 0.008856) ? _mathpow(y, (1 / 3)) : ((7.787 * y) + (16 / 116)));
    z = ((z > 0.008856) ? _mathpow(z, (1 / 3)) : ((7.787 * z) + (16 / 116)));
    return <dynamic>[((116 * y) - 16), (500 * (x - y)), (200 * (y - z))];
  }

  dynamic upstreamLabToRgb(dynamic L, dynamic a, dynamic b) {
    dynamic y = ((L + 16) / 116);
    dynamic x = ((a / 500) + y);
    dynamic z = (y - (b / 200));
    x = ((x > 0.206897) ? _mathpow(x, 3) : ((x - (16 / 116)) / 7.787));
    y = ((y > 0.206897) ? _mathpow(y, 3) : ((y - (16 / 116)) / 7.787));
    z = ((z > 0.206897) ? _mathpow(z, 3) : ((z - (16 / 116)) / 7.787));
    x = ((x * 95.047) / 100);
    y = ((y * 100) / 100);
    z = ((z * 108.883) / 100);
    dynamic r = (((x * 3.2404542) + (y * (-1.5371385))) + (z * (-0.4985314)));
    dynamic g = (((x * (-0.969266)) + (y * 1.8760108)) + (z * 0.041556));
    dynamic b2 = (((x * 0.0556434) + (y * (-0.2040259))) + (z * 1.0572252));
    r = ((r > 0.0031308)
        ? ((1.055 * _mathpow(r, (1 / 2.4))) - 0.055)
        : (12.92 * r));
    g = ((g > 0.0031308)
        ? ((1.055 * _mathpow(g, (1 / 2.4))) - 0.055)
        : (12.92 * g));
    b2 = ((b2 > 0.0031308)
        ? ((1.055 * _mathpow(b2, (1 / 2.4))) - 0.055)
        : (12.92 * b2));
    return <dynamic>[
      _mathmax(0, _mathmin(255, _mathround((r * 255)))),
      _mathmax(0, _mathmin(255, _mathround((g * 255)))),
      _mathmax(0, _mathmin(255, _mathround((b2 * 255)))),
    ];
  }

  dynamic upstreamClosest(dynamic r, dynamic g, dynamic b) {
    dynamic minDist = double.infinity;
    dynamic closest = 1;
    for (dynamic i = 0; (i < 7); i++) {
      if ((i == 4)) continue;
      dynamic p = UPSTREAM_PERCEIVED[i];
      dynamic dr = (r - p[0]);
      dynamic dg = (g - p[1]);
      dynamic db = (b - p[2]);
      dynamic dist = (((dr * dr) + (dg * dg)) + (db * db));
      if ((dist < minDist)) {
        minDist = dist;
        closest = i;
      }
    }
    return closest;
  }

  Future<dynamic> balancedToneMap(dynamic imageData) async {
    dynamic width = imageData["width"];
    dynamic height = imageData["height"];
    dynamic src = imageData["data"];
    dynamic n = (width * height);
    dynamic blackL = rgbToCielab(
      PALETTE_PERCEIVED[0][0],
      PALETTE_PERCEIVED[0][1],
      PALETTE_PERCEIVED[0][2],
    )[0];
    dynamic whiteL = rgbToCielab(
      PALETTE_PERCEIVED[1][0],
      PALETTE_PERCEIVED[1][1],
      PALETTE_PERCEIVED[1][2],
    )[0];
    dynamic toneL = _array("Float64Array", n);
    dynamic toneA = _array("Float64Array", n);
    dynamic toneB = _array("Float64Array", n);
    for (dynamic i = 0; (i < n); i++) {
      if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
      dynamic idx = (i * 4);
      dynamic lab = rgbToCielab(src[idx], src[(idx + 1)], src[(idx + 2)]);
      lab[0] = (blackL + ((lab[0] / 100) * (whiteL - blackL)));
      dynamic rgb = cielabToRgb(lab);
      dynamic oklab = rgbToOklab(rgb[0], rgb[1], rgb[2]);
      toneL[i] = oklab[0];
      toneA[i] = oklab[1];
      toneB[i] = oklab[2];
    }
    return <String, dynamic>{"toneL": toneL, "toneA": toneA, "toneB": toneB};
  }

  Future<dynamic> boxBlur(
    dynamic input,
    dynamic width,
    dynamic height,
    dynamic radius,
  ) async {
    dynamic n = (width * height);
    if ((radius <= 0)) {
      return input;
    }
    dynamic horizontal = _array("Float64Array", n);
    dynamic output = _array("Float64Array", n);
    for (dynamic y = 0; (y < height); y++) {
      if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
      dynamic sum = 0;
      dynamic count = 0;
      for (dynamic x = (-radius); (x <= radius); x++) {
        if (((x >= 0) && (x < width))) {
          sum += input[((y * width) + x)];
          count++;
        }
      }
      for (dynamic x2 = 0; (x2 < width); x2++) {
        horizontal[((y * width) + x2)] = (sum / count);
        dynamic removeX = (x2 - radius);
        dynamic addX = ((x2 + radius) + 1);
        if ((removeX >= 0)) {
          sum -= input[((y * width) + removeX)];
          count--;
        }
        if ((addX < width)) {
          sum += input[((y * width) + addX)];
          count++;
        }
      }
    }
    for (dynamic x3 = 0; (x3 < width); x3++) {
      if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
      dynamic sum2 = 0;
      dynamic count2 = 0;
      for (dynamic y2 = (-radius); (y2 <= radius); y2++) {
        if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
        if (((y2 >= 0) && (y2 < height))) {
          sum2 += horizontal[((y2 * width) + x3)];
          count2++;
        }
      }
      for (dynamic y3 = 0; (y3 < height); y3++) {
        if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
        output[((y3 * width) + x3)] = (sum2 / count2);
        dynamic removeY = (y3 - radius);
        dynamic addY = ((y3 + radius) + 1);
        if ((removeY >= 0)) {
          sum2 -= horizontal[((removeY * width) + x3)];
          count2--;
        }
        if ((addY < height)) {
          sum2 += horizontal[((addY * width) + x3)];
          count2++;
        }
      }
    }
    return output;
  }

  Future<dynamic> sobelMagnitude(
    dynamic input,
    dynamic width,
    dynamic height,
  ) async {
    dynamic n = (width * height);
    dynamic output = _array("Float64Array", n);
    for (dynamic y = 1; ((y + 1) < height); y++) {
      if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
      for (dynamic x = 1; ((x + 1) < width); x++) {
        dynamic at = (dynamic dx, dynamic dy) {
          return input[(((y + dy) * width) + (x + dx))];
        };
        dynamic gx =
            ((((((-at((-1), (-1))) + at(1, (-1))) - (2 * at((-1), 0))) +
                    (2 * at(1, 0))) -
                at((-1), 1)) +
            at(1, 1));
        dynamic gy =
            ((((((-at((-1), (-1))) - (2 * at(0, (-1)))) - at(1, (-1))) +
                    at((-1), 1)) +
                (2 * at(0, 1))) +
            at(1, 1));
        output[((y * width) + x)] = (_mathhypot(gx, gy) / 8);
      }
    }
    return output;
  }

  dynamic bilateralFilter(
    dynamic toneL,
    dynamic toneA,
    dynamic toneB,
    dynamic width,
    dynamic height,
    dynamic config,
  ) {
    if ((config["bilateralRadius"] <= 0)) {
      return <String, dynamic>{"toneL": toneL, "toneA": toneA, "toneB": toneB};
    }
    dynamic radius = config["bilateralRadius"];
    dynamic diameter = ((radius * 2) + 1);
    dynamic spatial = _array("Float64Array", (diameter * diameter));
    for (dynamic dy = (-radius); (dy <= radius); dy++) {
      for (dynamic dx = (-radius); (dx <= radius); dx++) {
        dynamic d2 = ((dx * dx) + (dy * dy));
        spatial[((((dy + radius) * diameter) + dx) + radius)] = _mathexp(
          ((-d2) /
              ((2 * config["bilateralSigmaSpatial"]) *
                  config["bilateralSigmaSpatial"])),
        );
      }
    }
    dynamic invL =
        (1 / ((2 * config["bilateralSigmaL"]) * config["bilateralSigmaL"]));
    dynamic invC =
        (1 /
        ((2 * config["bilateralSigmaChroma"]) *
            config["bilateralSigmaChroma"]));
    dynamic n = (width * height);
    dynamic outL = _array("Float64Array", n);
    dynamic outA = _array("Float64Array", n);
    dynamic outB = _array("Float64Array", n);
    for (dynamic y = 0; (y < height); y++) {
      for (dynamic x = 0; (x < width); x++) {
        dynamic pixel = ((y * width) + x);
        dynamic centerL = toneL[pixel];
        dynamic centerA = toneA[pixel];
        dynamic centerB = toneB[pixel];
        dynamic totalL = 0, totalA = 0, totalB = 0, totalWeight = 0;
        for (dynamic fy = (-radius); (fy <= radius); fy++) {
          dynamic ny = (y + fy);
          if (((ny < 0) || (ny >= height))) continue;
          for (dynamic fx = (-radius); (fx <= radius); fx++) {
            dynamic nx = (x + fx);
            if (((nx < 0) || (nx >= width))) continue;
            dynamic idx = ((ny * width) + nx);
            dynamic dl = (toneL[idx] - centerL);
            dynamic da = (toneA[idx] - centerA);
            dynamic db = (toneB[idx] - centerB);
            dynamic range = _mathexp(
              (-(((dl * dl) * invL) + (((da * da) + (db * db)) * invC))),
            );
            dynamic weight =
                (spatial[((((fy + radius) * diameter) + fx) + radius)] * range);
            totalL += (toneL[idx] * weight);
            totalA += (toneA[idx] * weight);
            totalB += (toneB[idx] * weight);
            totalWeight += weight;
          }
        }
        outL[pixel] = (totalL / totalWeight);
        outA[pixel] = (totalA / totalWeight);
        outB[pixel] = (totalB / totalWeight);
      }
    }
    return <String, dynamic>{"toneL": outL, "toneA": outA, "toneB": outB};
  }

  dynamic posterize(
    dynamic lab,
    dynamic config,
    dynamic panelBlack,
    dynamic panelWhite,
  ) {
    dynamic qL = lab[0];
    dynamic qA = lab[1];
    dynamic qB = lab[2];
    if ((config["posterLLevels"] > 1)) {
      dynamic normalized = clamp(
        ((lab[0] - panelBlack) / (panelWhite - panelBlack)),
        0,
        1,
      );
      dynamic level =
          (_mathround((normalized * (config["posterLLevels"] - 1))) /
          (config["posterLLevels"] - 1));
      qL = (panelBlack + (level * (panelWhite - panelBlack)));
    }
    dynamic sourceChroma = chroma(lab);
    if (((sourceChroma > 1e-8) && (config["posterCLevels"] > 1))) {
      dynamic kChromaCeiling = 0.32;
      dynamic normC = clamp((sourceChroma / kChromaCeiling), 0, 1);
      dynamic quantizedChroma =
          ((_mathround((normC * (config["posterCLevels"] - 1))) /
              (config["posterCLevels"] - 1)) *
          kChromaCeiling);
      dynamic hue = _mathatan2(lab[2], lab[1]);
      if ((config["posterHBins"] > 1)) {
        dynamic step = ((2 * PI) / config["posterHBins"]);
        hue = (_mathround((hue / step)) * step);
      }
      qA = (quantizedChroma * _mathcos(hue));
      qB = (quantizedChroma * _mathsin(hue));
    }
    return oklabMix(lab, <dynamic>[qL, qA, qB], config["posterBlend"]);
  }

  dynamic classifyHue(dynamic lab, dynamic neutralThreshold) {
    if ((chroma(lab) < neutralThreshold)) {
      return 0;
    }
    dynamic hue = ((_mathatan2(lab[2], lab[1]) * 180) / PI);
    if (((hue >= (-30)) && (hue < 115))) return 1;
    if ((hue >= 115)) return 2;
    if ((hue < (-55))) return 3;
    return 4;
  }

  dynamic allowedMask(dynamic hueClass) {
    dynamic blackWhite = ((1 << 0) | (1 << 1));
    switch (hueClass) {
      case 0:
        return blackWhite;
      case 1:
        return ((blackWhite | (1 << 2)) | (1 << 3));
      case 2:
        return ((blackWhite | (1 << 2)) | (1 << 4));
      case 3:
        return ((blackWhite | (1 << 4)) | (1 << 5));
      case 4:
        return ((blackWhite | (1 << 3)) | (1 << 5));
    }
    return blackWhite;
  }

  dynamic nearestPaletteRgb(
    dynamic target,
    dynamic availableMask,
    dynamic preferredMask,
    dynamic crossHuePenalty,
  ) {
    dynamic best = 0;
    dynamic bestScore = double.infinity;
    for (dynamic i = 0; (i < 6); i++) {
      if (((availableMask & (1 << i)) == 0)) {
        continue;
      }
      dynamic p = PALETTE_PERCEIVED[i];
      dynamic score = squaredRgbDistance(target, p);
      if (((preferredMask & (1 << i)) == 0)) {
        score += crossHuePenalty;
      }
      if ((score < bestScore)) {
        bestScore = score;
        best = i;
      }
    }
    return best;
  }

  Future<dynamic> dilateMask(
    dynamic input,
    dynamic width,
    dynamic height,
    dynamic radius,
  ) async {
    dynamic n = (width * height);
    dynamic output = _array("Uint8Array", n);
    for (dynamic y = 0; (y < height); y++) {
      if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
      for (dynamic x = 0; (x < width); x++) {
        dynamic found = false;
        for (
          dynamic dy = (-radius);
          ((dy <= radius) && (!_truth(found)));
          dy++
        ) {
          dynamic ny = (y + dy);
          if (((ny < 0) || (ny >= height))) continue;
          for (dynamic dx = (-radius); (dx <= radius); dx++) {
            dynamic nx = (x + dx);
            if ((((nx >= 0) && (nx < width)) &&
                _truth(input[((ny * width) + nx)]))) {
              found = true;
              break;
            }
          }
        }
        output[((y * width) + x)] = (_truth(found) ? 1 : 0);
      }
    }
    return output;
  }

  Future<dynamic> detectFilmStrips(
    dynamic toneL,
    dynamic width,
    dynamic height,
    dynamic panelBlack,
  ) async {
    dynamic darkFraction = _array("Float64Array", width);
    for (dynamic x = 0; (x < width); x++) {
      if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
      dynamic dark = 0;
      for (dynamic y = 0; (y < height); y++) {
        if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
        if ((toneL[((y * width) + x)] < (panelBlack + 0.2))) {
          dark++;
        }
      }
      darkFraction[x] = (dark / height);
    }
    dynamic leftExclusive = 0;
    dynamic rightBegin = width;
    while (((leftExclusive < _mathfloor((width / 4))) &&
        (darkFraction[leftExclusive] > 0.6))) {
      leftExclusive++;
    }
    while (((rightBegin > _mathfloor(((width * 3) / 4))) &&
        (darkFraction[(rightBegin - 1)] > 0.6))) {
      rightBegin--;
    }
    if ((leftExclusive < 8)) leftExclusive = 0;
    if ((rightBegin > (width - 8))) rightBegin = width;
    return <String, dynamic>{
      "leftExclusive": leftExclusive,
      "rightBegin": rightBegin,
    };
  }

  Future<dynamic> v5SeedDither(dynamic imageData) async {
    dynamic width = imageData["width"];
    dynamic height = imageData["height"];
    dynamic src = imageData["data"];
    dynamic n = (width * height);
    dynamic blackL = upstreamRgbToLab(2, 2, 2)[0];
    dynamic whiteL = upstreamRgbToLab(190, 200, 200)[0];
    dynamic comp = _array("Uint8ClampedArray", (n * 3));
    for (dynamic i = 0; (i < n); i++) {
      if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
      dynamic idx = (i * 4);
      dynamic lab = upstreamRgbToLab(src[idx], src[(idx + 1)], src[(idx + 2)]);
      dynamic compressedL = (blackL + ((lab[0] / 100) * (whiteL - blackL)));
      dynamic rgb = upstreamLabToRgb(compressedL, lab[1], lab[2]);
      comp[(i * 3)] = rgb[0];
      comp[((i * 3) + 1)] = rgb[1];
      comp[((i * 3) + 2)] = rgb[2];
    }
    dynamic errors = _array("Float64Array", (n * 3));
    dynamic labels = _array("Uint8Array", n);
    for (dynamic y = 0; (y < height); y++) {
      if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
      for (dynamic x = 0; (x < width); x++) {
        dynamic p = ((y * width) + x);
        dynamic e = (p * 3);
        dynamic wR = clamp((comp[e] + errors[e]), 0, 255);
        dynamic wG = clamp((comp[(e + 1)] + errors[(e + 1)]), 0, 255);
        dynamic wB = clamp((comp[(e + 2)] + errors[(e + 2)]), 0, 255);
        dynamic colorIdx = upstreamClosest(wR, wG, wB);
        labels[p] = UPSTREAM_TO_LABEL[colorIdx];
        dynamic ditherColor = UPSTREAM_PERCEIVED[colorIdx];
        dynamic errR = (wR - ditherColor[0]);
        dynamic errG = (wG - ditherColor[1]);
        dynamic errB = (wB - ditherColor[2]);
        for (dynamic t = 0; (t < FS_TAPS.length); t++) {
          dynamic tap = FS_TAPS[t];
          dynamic nx = (x + tap[0]);
          dynamic ny = (y + tap[1]);
          if (((((nx < 0) || (nx >= width)) || (ny < 0)) || (ny >= height)))
            continue;
          dynamic ni = (((ny * width) + nx) * 3);
          errors[ni] += (errR * tap[2]);
          errors[(ni + 1)] += (errG * tap[2]);
          errors[(ni + 2)] += (errB * tap[2]);
        }
      }
    }
    return labels;
  }

  Future<dynamic> quantize(
    dynamic tone,
    dynamic grad,
    dynamic filmStrips,
    dynamic config,
    dynamic perceived,
    dynamic seedLabels,
  ) async {
    dynamic width = tone["width"];
    dynamic height = tone["height"];
    dynamic n = (width * height);
    dynamic toneL = tone["toneL"], toneA = tone["toneA"], toneB = tone["toneB"];
    dynamic panelBlack = perceived[0][0];
    dynamic panelWhite = perceived[1][0];
    dynamic baseL = _array("Float64Array", n);
    dynamic baseA = _array("Float64Array", n);
    dynamic baseB = _array("Float64Array", n);
    dynamic baseR = _array("Float64Array", n);
    dynamic baseG = _array("Float64Array", n);
    dynamic baseBlu = _array("Float64Array", n);
    for (dynamic y = 0; (y < height); y++) {
      if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
      for (dynamic x = 0; (x < width); x++) {
        dynamic pixel = ((y * width) + x);
        dynamic structure = smoothstep(
          config["edgeLow"],
          config["edgeHigh"],
          grad[pixel],
        );
        dynamic keep =
            (config["detailKeepFlat"] +
            ((1 - config["detailKeepFlat"]) * structure));
        dynamic reduced = oklabMix(
          <dynamic>[toneL[pixel], toneA[pixel], toneB[pixel]],
          <dynamic>[toneL[pixel], toneA[pixel], toneB[pixel]],
          keep,
        );
        dynamic baseLab = posterize(reduced, config, panelBlack, panelWhite);
        baseL[pixel] = baseLab[0];
        baseA[pixel] = baseLab[1];
        baseB[pixel] = baseLab[2];
        dynamic rgb = oklabToRgb(baseLab);
        baseR[pixel] = rgb[0];
        baseG[pixel] = rgb[1];
        baseBlu[pixel] = rgb[2];
      }
    }
    dynamic classes = _array("Uint8Array", n);
    dynamic preferred = _array("Uint8Array", n);
    dynamic available = _array("Uint8Array", n);
    dynamic deepBlack = _array("Uint8Array", n);
    dynamic textSeed = _array("Uint8Array", n);
    for (dynamic y2 = 0; (y2 < height); y2++) {
      if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
      for (dynamic x2 = 0; (x2 < width); x2++) {
        dynamic p2 = ((y2 * width) + x2);
        dynamic baseLab2 = <dynamic>[baseL[p2], baseA[p2], baseB[p2]];
        classes[p2] = classifyHue(baseLab2, config["neutralChroma"]);
        preferred[p2] = allowedMask(classes[p2]);
        available[p2] = 63;
        deepBlack[p2] = ((toneL[p2] < (panelBlack + config["deepBlackMargin"]))
            ? 1
            : 0);
        if (_truth(deepBlack[p2])) {
          preferred[p2] = (1 << 0);
          available[p2] = (1 << 0);
        }
        dynamic localMin = toneL[p2];
        for (dynamic dy = (-1); (dy <= 1); dy++) {
          dynamic ny2 = (y2 + dy);
          if (((ny2 < 0) || (ny2 >= height))) continue;
          for (dynamic dx = (-1); (dx <= 1); dx++) {
            dynamic nx2 = (x2 + dx);
            if (((nx2 >= 0) && (nx2 < width))) {
              localMin = _mathmin(localMin, toneL[((ny2 * width) + nx2)]);
            }
          }
        }
        textSeed[p2] =
            ((((chroma(<dynamic>[toneL[p2], toneA[p2], toneB[p2]]) > 0.06) &&
                    (grad[p2] > config["edgeLow"])) &&
                ((toneL[p2] - localMin) > 0.035))
            ? 1
            : 0);
      }
    }
    dynamic textNeighborhood = await dilateMask(textSeed, width, height, 1);
    dynamic textProtect = _array("Uint8Array", n);
    for (dynamic p3 = 0; (p3 < n); p3++) {
      if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
      textProtect[p3] =
          ((_truth(textNeighborhood[p3]) &&
              (chroma(<dynamic>[toneL[p3], toneA[p3], toneB[p3]]) >
                  (config["neutralChroma"] * 1.25)))
          ? 1
          : 0);
      if (_truth(textProtect[p3])) {
        available[p3] = preferred[p3];
      }
    }
    dynamic errorsR = _array("Float64Array", n);
    dynamic errorsG = _array("Float64Array", n);
    dynamic errorsB = _array("Float64Array", n);
    dynamic labels = _array("Uint8Array", n);
    for (dynamic y3 = 0; (y3 < height); y3++) {
      if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
      dynamic reverse = ((y3 & 1) != 0);
      for (dynamic step = 0; (step < width); step++) {
        dynamic x3 = (_truth(reverse) ? ((width - 1) - step) : step);
        dynamic px = ((y3 * width) + x3);
        dynamic structure2 = smoothstep(
          config["edgeLow"],
          config["edgeHigh"],
          grad[px],
        );
        dynamic protectedPixel =
            ((_truth(textProtect[px]) || (structure2 > 0.82)) ||
            _truth(deepBlack[px]));
        dynamic errorApply = (_truth(protectedPixel) ? 0 : (1 - structure2));
        dynamic working = <dynamic>[
          clamp((baseR[px] + (errorsR[px] * errorApply)), 0, 255),
          clamp((baseG[px] + (errorsG[px] * errorApply)), 0, 255),
          clamp((baseBlu[px] + (errorsB[px] * errorApply)), 0, 255),
        ];
        dynamic selected = nearestPaletteRgb(
          working,
          available[px],
          preferred[px],
          config["crossHuePenalty"],
        );
        labels[px] = selected;
        if (_truth(protectedPixel)) {
          continue;
        }
        dynamic per = PALETTE_PERCEIVED[selected];
        dynamic errR = (working[0] - per[0]);
        dynamic errG = (working[1] - per[1]);
        dynamic errB = (working[2] - per[2]);
        dynamic localL = (config["ditherL"] * (1 - structure2));
        dynamic localC = (config["ditherC"] * (1 - structure2));
        dynamic luminanceError =
            (((0.2126 * errR) + (0.7152 * errG)) + (0.0722 * errB));
        errR = clamp(
          ((luminanceError * localL) + ((errR - luminanceError) * localC)),
          (-255),
          255,
        );
        errG = clamp(
          ((luminanceError * localL) + ((errG - luminanceError) * localC)),
          (-255),
          255,
        );
        errB = clamp(
          ((luminanceError * localL) + ((errB - luminanceError) * localC)),
          (-255),
          255,
        );
        for (dynamic t = 0; (t < FS_TAPS.length); t++) {
          dynamic tap = FS_TAPS[t];
          dynamic ddx = (_truth(reverse) ? (-tap[0]) : tap[0]);
          dynamic nx3 = (x3 + ddx);
          dynamic ny3 = (y3 + tap[1]);
          if (((((nx3 < 0) || (nx3 >= width)) || (ny3 < 0)) || (ny3 >= height)))
            continue;
          dynamic target = ((ny3 * width) + nx3);
          if ((_truth(textProtect[target]) || _truth(deepBlack[target])))
            continue;
          dynamic dl = _mathabs((baseL[px] - baseL[target]));
          dynamic dc = _mathhypot(
            (baseA[px] - baseA[target]),
            (baseB[px] - baseB[target]),
          );
          dynamic barrier = _mathexp(
            (((-dl) / config["errorBarrierL"]) -
                (dc / config["errorBarrierC"])),
          );
          if ((classes[px] != classes[target])) {
            barrier *= 0.08;
          }
          dynamic targetStructure = smoothstep(
            config["edgeLow"],
            config["edgeHigh"],
            grad[target],
          );
          barrier *= (1 - (0.92 * targetStructure));
          dynamic weight = (tap[2] * barrier);
          errorsR[target] += (errR * weight);
          errorsG[target] += (errG * weight);
          errorsB[target] += (errB * weight);
        }
      }
    }
    if ((seedLabels != null)) {
      _set(labels, seedLabels);
      dynamic leftTextLimit = _mathceil(
        (filmStrips["leftExclusive"] * config["leftTextOuterFraction"]),
      );
      dynamic leftText = _array("Uint8Array", n);
      dynamic rightText = _array("Uint8Array", n);
      dynamic perceivedLuma = (dynamic color) {
        return (((0.2126 * color[0]) + (0.7152 * color[1])) +
            (0.0722 * color[2]));
      };
      dynamic blackLuma = perceivedLuma(PALETTE_PERCEIVED[0]);
      dynamic yellowLuma = perceivedLuma(PALETTE_PERCEIVED[2]);
      for (dynamic y4 = 0; (y4 < height); y4++) {
        if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
        for (dynamic x4 = 0; (x4 < width); x4++) {
          dynamic p4 = ((y4 * width) + x4);
          if ((x4 < leftTextLimit)) {
            leftText[p4] =
                ((((chroma(<dynamic>[toneL[p4], toneA[p4], toneB[p4]]) >
                            config["leftTextChroma"]) &&
                        (toneB[p4] > config["leftTextB"])) &&
                    (toneL[p4] > (panelBlack + config["leftTextLMargin"])))
                ? 1
                : 0);
          }
          if ((x4 >= filmStrips["rightBegin"])) {
            rightText[p4] =
                ((((chroma(<dynamic>[toneL[p4], toneA[p4], toneB[p4]]) >
                            0.065) &&
                        (toneA[p4] > 0.03)) &&
                    (toneL[p4] > (panelBlack + 0.045)))
                ? 1
                : 0);
          }
        }
      }
      dynamic allText = _array("Uint8Array", n);
      for (dynamic p5 = 0; (p5 < n); p5++) {
        if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
        allText[p5] = ((_truth(leftText[p5]) || _truth(rightText[p5])) ? 1 : 0);
      }
      dynamic textGuard = await dilateMask(allText, width, height, 2);
      for (dynamic pass = 0; (pass < config["refinePasses"]); pass++) {
        if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
        dynamic refined = _array("Uint8Array", labels);
        for (dynamic y5 = 0; (y5 < height); y5++) {
          if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
          for (dynamic x5 = 0; (x5 < width); x5++) {
            dynamic p6 = ((y5 * width) + x5);
            dynamic border =
                ((x5 < filmStrips["leftExclusive"]) ||
                (x5 >= filmStrips["rightBegin"]));
            if (_truth(leftText[p6])) {
              dynamic seedLabel = seedLabels[p6];
              if ((seedLabel == 2)) {
                refined[p6] = 2;
              } else {
                dynamic seedLuma = perceivedLuma(PALETTE_PERCEIVED[seedLabel]);
                dynamic baseCoverage = clamp(
                  ((seedLuma - blackLuma) /
                      _mathmax(1e-9, (yellowLuma - blackLuma))),
                  0,
                  1,
                );
                dynamic coverage = clamp(
                  (baseCoverage * config["leftTextEdgeScale"]),
                  0,
                  1,
                );
                dynamic threshold =
                    ((BAYER8[(((y5 & 7) * 8) + (x5 & 7))] + 0.5) / 64);
                refined[p6] = ((coverage > threshold) ? 2 : 0);
              }
              continue;
            }
            if (_truth(rightText[p6])) {
              refined[p6] = 3;
              continue;
            }
            if ((_truth(border) && (toneL[p6] < (panelBlack + 0.155)))) {
              refined[p6] = 0;
              continue;
            }
            if (((((((((x5 == 0) || (y5 == 0)) || ((x5 + 1) == width)) ||
                                ((y5 + 1) == height)) ||
                            (grad[p6] >= config["refineEdge"])) ||
                        (toneL[p6] < config["refineMinL"])) ||
                    _truth(textGuard[p6])) ||
                (config["refineSameNeighbors"] < 0))) {
              continue;
            }
            dynamic current = labels[p6];
            if (((current < 2) || ((preferred[p6] & (1 << current)) != 0))) {
              continue;
            }
            dynamic same = 0;
            for (dynamic dy2 = (-1); (dy2 <= 1); dy2++) {
              for (dynamic dx2 = (-1); (dx2 <= 1); dx2++) {
                if (((dx2 == 0) && (dy2 == 0))) continue;
                same +=
                    ((labels[(((y5 + dy2) * width) + (x5 + dx2))] == current)
                    ? 1
                    : 0);
              }
            }
            if ((same > config["refineSameNeighbors"])) {
              continue;
            }
            dynamic replacement = nearestPaletteRgb(
              <dynamic>[baseR[p6], baseG[p6], baseBlu[p6]],
              preferred[p6],
              preferred[p6],
              0,
            );
            dynamic currentError = squaredRgbDistance(<dynamic>[
              baseR[p6],
              baseG[p6],
              baseBlu[p6],
            ], PALETTE_PERCEIVED[current]);
            dynamic replacementError = squaredRgbDistance(<dynamic>[
              baseR[p6],
              baseG[p6],
              baseBlu[p6],
            ], PALETTE_PERCEIVED[replacement]);
            if ((replacementError <=
                (currentError + config["refineTolerance"]))) {
              refined[p6] = replacement;
            }
          }
        }
        labels = refined;
      }
    }
    if ((config["sparkleSweeps"] > 0)) {
      dynamic isBrightLabel = (dynamic label) {
        return (perceived[label][0] >= config["sparkleBrightL"]);
      };
      dynamic brightNeighbors = (dynamic pixel, dynamic excluded) {
        dynamic bx = (pixel % width);
        dynamic by = _mathfloor((pixel / width));
        dynamic count = 0;
        for (dynamic dy3 = (-1); (dy3 <= 1); dy3++) {
          for (dynamic dx3 = (-1); (dx3 <= 1); dx3++) {
            if (((dx3 == 0) && (dy3 == 0))) continue;
            dynamic nx4 = (bx + dx3);
            dynamic ny4 = (by + dy3);
            if (((((nx4 < 0) || (nx4 >= width)) || (ny4 < 0)) ||
                (ny4 >= height)))
              continue;
            if (((((ny4 * width) + nx4) != excluded) &&
                _truth(isBrightLabel(labels[((ny4 * width) + nx4)])))) {
              count++;
            }
          }
        }
        return count;
      };
      dynamic salientSingletonSweep = (dynamic pixel) {
        dynamic sx = (pixel % width);
        dynamic sy = _mathfloor((pixel / width));
        if ((((((((((((sx == 0) || (sy == 0)) || ((sx + 1) == width)) ||
                                        ((sy + 1) == height)) ||
                                    (sx < filmStrips["leftExclusive"])) ||
                                (sx >= filmStrips["rightBegin"])) ||
                            _truth(textProtect[pixel])) ||
                        _truth(deepBlack[pixel])) ||
                    (grad[pixel] >= config["sparkleEdge"])) ||
                (!_truth(isBrightLabel(labels[pixel])))) ||
            (brightNeighbors(pixel, n) != 0))) {
          return false;
        }
        dynamic outputNeighborL = 0;
        dynamic sourceNeighborL = 0;
        dynamic count = 0;
        for (dynamic dy4 = (-1); (dy4 <= 1); dy4++) {
          for (dynamic dx4 = (-1); (dx4 <= 1); dx4++) {
            if (((dx4 == 0) && (dy4 == 0))) continue;
            dynamic nb = (((sy + dy4) * width) + (sx + dx4));
            outputNeighborL += perceived[labels[nb]][0];
            sourceNeighborL += toneL[nb];
            count++;
          }
        }
        outputNeighborL /= count;
        sourceNeighborL /= count;
        dynamic outputSpike =
            ((perceived[labels[pixel]][0] - outputNeighborL) >=
            config["sparkleLumaDelta"]);
        dynamic realSourceHighlight =
            ((toneL[pixel] - sourceNeighborL) > config["sparkleSourceDelta"]);
        return (_truth(outputSpike) && (!_truth(realSourceHighlight)));
      };
      dynamic dataCost = (dynamic pixel, dynamic label) {
        dynamic cost = squaredDistance(<dynamic>[
          baseL[pixel],
          baseA[pixel],
          baseB[pixel],
        ], perceived[label]);
        if (((preferred[pixel] & (1 << label)) == 0)) {
          cost += config["crossHuePenalty"];
        }
        return cost;
      };
      for (dynamic sweep = 0; (sweep < config["sparkleSweeps"]); sweep++) {
        if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
        dynamic used = _array("Uint8Array", n);
        dynamic reverseRows = ((sweep & 1) != 0);
        for (dynamic rowStep = 1; ((rowStep + 1) < height); rowStep++) {
          if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
          dynamic sy2 = (_truth(reverseRows)
              ? ((height - 1) - rowStep)
              : rowStep);
          dynamic reverseColumns = (((sy2 + sweep) & 1) != 0);
          for (
            dynamic colStep = filmStrips["leftExclusive"];
            (colStep < filmStrips["rightBegin"]);
            colStep++
          ) {
            dynamic sx2 = (_truth(reverseColumns)
                ? ((filmStrips["rightBegin"] - 1) -
                      (colStep - filmStrips["leftExclusive"]))
                : colStep);
            dynamic sp = ((sy2 * width) + sx2);
            if ((_truth(used[sp]) || (!_truth(salientSingletonSweep(sp)))))
              continue;
            dynamic bestAnchor = (-1);
            dynamic bestDestination = (-1);
            dynamic bestScore = double.infinity;
            for (
              dynamic ay = (sy2 - config["sparkleRadius"]);
              (ay <= (sy2 + config["sparkleRadius"]));
              ay++
            ) {
              if (((ay <= 0) || ((ay + 1) >= height))) continue;
              for (
                dynamic ax = (sx2 - config["sparkleRadius"]);
                (ax <= (sx2 + config["sparkleRadius"]));
                ax++
              ) {
                if ((((ax < filmStrips["leftExclusive"]) ||
                        (ax >= filmStrips["rightBegin"])) ||
                    ((ax == sx2) && (ay == sy2))))
                  continue;
                dynamic anchor = ((ay * width) + ax);
                if ((_truth(used[anchor]) ||
                    (!_truth(salientSingletonSweep(anchor)))))
                  continue;
                for (dynamic dy5 = (-1); (dy5 <= 1); dy5++) {
                  for (dynamic dx5 = (-1); (dx5 <= 1); dx5++) {
                    if (((dx5 == 0) && (dy5 == 0))) continue;
                    dynamic qx = (ax + dx5);
                    dynamic qy = (ay + dy5);
                    if (((((qx < filmStrips["leftExclusive"]) ||
                                (qx >= filmStrips["rightBegin"])) ||
                            (qy <= 0)) ||
                        ((qy + 1) >= height)))
                      continue;
                    dynamic dest = ((qy * width) + qx);
                    if ((((((((((dest == sp) || _truth(used[dest])) ||
                                                _truth(
                                                  isBrightLabel(labels[dest]),
                                                )) ||
                                            _truth(textProtect[dest])) ||
                                        _truth(deepBlack[dest])) ||
                                    (grad[dest] >= config["sparkleEdge"])) ||
                                (classes[sp] != classes[dest])) ||
                            ((preferred[sp] & (1 << labels[dest])) == 0)) ||
                        ((preferred[dest] & (1 << labels[sp])) == 0))) {
                      continue;
                    }
                    dynamic sourceDistance = _mathsqrt(
                      squaredDistance(
                        <dynamic>[baseL[sp], baseA[sp], baseB[sp]],
                        <dynamic>[baseL[dest], baseA[dest], baseB[dest]],
                      ),
                    );
                    if (((sourceDistance > config["sparkleSourceDistance"]) ||
                        ((baseL[dest] + config["sparkleSourceDelta"]) <
                            baseL[sp]))) {
                      continue;
                    }
                    dynamic dataDelta =
                        (((dataCost(sp, labels[dest]) +
                                dataCost(dest, labels[sp])) -
                            dataCost(sp, labels[sp])) -
                        dataCost(dest, labels[dest]));
                    if ((dataDelta > config["sparkleDataTolerance"])) continue;
                    dynamic score =
                        ((dataDelta + (0.1 * sourceDistance)) -
                        (0.04 * (baseL[dest] - baseL[sp])));
                    if ((score < bestScore)) {
                      bestScore = score;
                      bestAnchor = anchor;
                      bestDestination = dest;
                    }
                  }
                }
              }
            }
            if ((bestDestination != (-1))) {
              dynamic tmp = labels[sp];
              labels[sp] = labels[bestDestination];
              labels[bestDestination] = tmp;
              used[sp] = 1;
              used[bestDestination] = 1;
              used[bestAnchor] = 1;
            }
          }
        }
      }
    }
    if ((config["sparkleCleanupPasses"] > 0)) {
      dynamic isBright2 = (dynamic label) {
        return (perceived[label][0] >= config["sparkleBrightL"]);
      };
      dynamic salientSingletonCleanup = (dynamic pixel) {
        dynamic sx = (pixel % width);
        dynamic sy = _mathfloor((pixel / width));
        if (((((((((((sx == 0) || (sy == 0)) || ((sx + 1) == width)) ||
                                    ((sy + 1) == height)) ||
                                (sx < filmStrips["leftExclusive"])) ||
                            (sx >= filmStrips["rightBegin"])) ||
                        _truth(textProtect[pixel])) ||
                    _truth(deepBlack[pixel])) ||
                (grad[pixel] >= config["sparkleEdge"])) ||
            (!_truth(isBright2(labels[pixel]))))) {
          return false;
        }
        dynamic nearbyBright = 0;
        dynamic outputNeighborL = 0;
        dynamic sourceNeighborL = 0;
        for (dynamic dy6 = (-1); (dy6 <= 1); dy6++) {
          for (dynamic dx6 = (-1); (dx6 <= 1); dx6++) {
            if (((dx6 == 0) && (dy6 == 0))) continue;
            dynamic nb2 = (((sy + dy6) * width) + (sx + dx6));
            if (_truth(isBright2(labels[nb2]))) nearbyBright++;
            outputNeighborL += perceived[labels[nb2]][0];
            sourceNeighborL += toneL[nb2];
          }
        }
        outputNeighborL /= 8;
        sourceNeighborL /= 8;
        return (((nearbyBright == 0) &&
                ((perceived[labels[pixel]][0] - outputNeighborL) >=
                    config["sparkleLumaDelta"])) &&
            ((toneL[pixel] - sourceNeighborL) <= config["sparkleSourceDelta"]));
      };
      for (
        dynamic pass2 = 0;
        (pass2 < config["sparkleCleanupPasses"]);
        pass2++
      ) {
        if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
        dynamic cleaned = _array("Uint8Array", labels);
        for (dynamic y6 = 1; ((y6 + 1) < height); y6++) {
          if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
          for (
            dynamic x6 = _mathmax(1, filmStrips["leftExclusive"]);
            ((x6 + 1) < filmStrips["rightBegin"]);
            x6++
          ) {
            dynamic sp2 = ((y6 * width) + x6);
            if ((!_truth(salientSingletonCleanup(sp2)))) continue;
            dynamic radius = config["sparkleCleanupWindow"];
            dynamic srcTotal = <dynamic>[0, 0, 0];
            dynamic outTotal = <dynamic>[0, 0, 0];
            dynamic localCounts = <dynamic>[0, 0, 0, 0, 0, 0];
            dynamic count2 = 0;
            for (dynamic dy7 = (-radius); (dy7 <= radius); dy7++) {
              dynamic ny5 = (y6 + dy7);
              if (((ny5 < 0) || (ny5 >= height))) continue;
              for (dynamic dx7 = (-radius); (dx7 <= radius); dx7++) {
                dynamic nx5 = (x6 + dx7);
                if (((nx5 < filmStrips["leftExclusive"]) ||
                    (nx5 >= filmStrips["rightBegin"])))
                  continue;
                dynamic nb3 = ((ny5 * width) + nx5);
                srcTotal[0] += baseL[nb3];
                srcTotal[1] += baseA[nb3];
                srcTotal[2] += baseB[nb3];
                dynamic pl = perceived[labels[nb3]];
                outTotal[0] += pl[0];
                outTotal[1] += pl[1];
                outTotal[2] += pl[2];
                localCounts[labels[nb3]]++;
                count2++;
              }
            }
            dynamic sourceAverage = <dynamic>[
              (srcTotal[0] / count2),
              (srcTotal[1] / count2),
              (srcTotal[2] / count2),
            ];
            dynamic outputAverage = <dynamic>[
              (outTotal[0] / count2),
              (outTotal[1] / count2),
              (outTotal[2] / count2),
            ];
            dynamic beforeError = squaredDistance(sourceAverage, outputAverage);
            dynamic current2 = labels[sp2];
            dynamic best2 = current2;
            dynamic bestError = beforeError;
            for (dynamic candidate = 0; (candidate < 6); candidate++) {
              if (((((candidate == current2) || _truth(isBright2(candidate))) ||
                      (localCounts[candidate] == 0)) ||
                  ((preferred[sp2] & (1 << candidate)) == 0))) {
                continue;
              }
              dynamic shifted = <dynamic>[
                (((outTotal[0] - perceived[current2][0]) +
                        perceived[candidate][0]) /
                    count2),
                (((outTotal[1] - perceived[current2][1]) +
                        perceived[candidate][1]) /
                    count2),
                (((outTotal[2] - perceived[current2][2]) +
                        perceived[candidate][2]) /
                    count2),
              ];
              dynamic afterError = squaredDistance(sourceAverage, shifted);
              if (((afterError <=
                      (beforeError + config["sparkleDataTolerance"])) &&
                  (afterError <
                      (bestError + config["sparkleDataTolerance"])))) {
                dynamic directBefore = squaredDistance(<dynamic>[
                  baseL[sp2],
                  baseA[sp2],
                  baseB[sp2],
                ], perceived[current2]);
                dynamic directAfter = squaredDistance(<dynamic>[
                  baseL[sp2],
                  baseA[sp2],
                  baseB[sp2],
                ], perceived[candidate]);
                dynamic score2 = (afterError + (0.002 * directAfter));
                dynamic bestScore2 =
                    (bestError +
                    (0.002 *
                        squaredDistance(<dynamic>[
                          baseL[sp2],
                          baseA[sp2],
                          baseB[sp2],
                        ], perceived[best2])));
                if (((score2 < bestScore2) &&
                    (directAfter <= (directBefore + 0.12)))) {
                  best2 = candidate;
                  bestError = afterError;
                }
              }
            }
            cleaned[sp2] = best2;
          }
        }
        labels = cleaned;
      }
    }
    if ((config["chromaRelocateSweeps"] > 0)) {
      dynamic dataCost2 = (dynamic pixel, dynamic label) {
        dynamic cost = squaredDistance(<dynamic>[
          baseL[pixel],
          baseA[pixel],
          baseB[pixel],
        ], perceived[label]);
        if (((preferred[pixel] & (1 << label)) == 0)) {
          cost += config["crossHuePenalty"];
        }
        return cost;
      };
      dynamic sameNeighbors = (dynamic pixel, dynamic label) {
        dynamic bx = (pixel % width);
        dynamic by = _mathfloor((pixel / width));
        dynamic same2 = 0;
        for (dynamic dy8 = (-1); (dy8 <= 1); dy8++) {
          for (dynamic dx8 = (-1); (dx8 <= 1); dx8++) {
            if (((dx8 == 0) && (dy8 == 0))) continue;
            dynamic nx6 = (bx + dx8);
            dynamic ny6 = (by + dy8);
            if (((((nx6 < 0) || (nx6 >= width)) || (ny6 < 0)) ||
                (ny6 >= height)))
              continue;
            if ((labels[((ny6 * width) + nx6)] == label)) same2++;
          }
        }
        return same2;
      };
      for (
        dynamic sweep2 = 0;
        (sweep2 < config["chromaRelocateSweeps"]);
        sweep2++
      ) {
        if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
        dynamic used2 = _array("Uint8Array", n);
        for (dynamic y7 = 1; ((y7 + 1) < height); y7++) {
          if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
          for (
            dynamic x7 = _mathmax(1, filmStrips["leftExclusive"]);
            ((x7 + 1) < filmStrips["rightBegin"]);
            x7++
          ) {
            dynamic sp3 = ((y7 * width) + x7);
            dynamic cur = labels[sp3];
            if (((((((_truth(used2[sp3]) || (cur < 4)) ||
                                _truth(textProtect[sp3])) ||
                            _truth(deepBlack[sp3])) ||
                        (grad[sp3] >= config["sparkleEdge"])) ||
                    ((preferred[sp3] & (1 << cur)) != 0)) ||
                (sameNeighbors(sp3, cur) > 1))) {
              continue;
            }
            dynamic best3 = (-1);
            dynamic bestScore3 = 0;
            for (
              dynamic dy9 = (-config["chromaRelocateRadius"]);
              (dy9 <= config["chromaRelocateRadius"]);
              dy9++
            ) {
              dynamic qy2 = (y7 + dy9);
              if (((qy2 <= 0) || ((qy2 + 1) >= height))) continue;
              for (
                dynamic dx9 = (-config["chromaRelocateRadius"]);
                (dx9 <= config["chromaRelocateRadius"]);
                dx9++
              ) {
                dynamic qx2 = (x7 + dx9);
                if (((((dx9 == 0) && (dy9 == 0)) ||
                        (qx2 < filmStrips["leftExclusive"])) ||
                    (qx2 >= filmStrips["rightBegin"]))) {
                  continue;
                }
                dynamic dest2 = ((qy2 * width) + qx2);
                dynamic destLabel = labels[dest2];
                if ((((((_truth(used2[dest2]) || (destLabel == cur)) ||
                                _truth(textProtect[dest2])) ||
                            _truth(deepBlack[dest2])) ||
                        (grad[dest2] >= config["chromaRelocateEdge"])) ||
                    ((preferred[sp3] & (1 << destLabel)) == 0))) {
                  continue;
                }
                dynamic before2 =
                    (dataCost2(sp3, cur) + dataCost2(dest2, destLabel));
                dynamic after2 =
                    (dataCost2(sp3, destLabel) + dataCost2(dest2, cur));
                if ((after2 > (before2 + config["chromaRelocateTolerance"])))
                  continue;
                dynamic attached = sameNeighbors(dest2, cur);
                dynamic score3 =
                    (((after2 - before2) - (0.0015 * attached)) -
                    (0.002 * grad[dest2]));
                if (((best3 == (-1)) || (score3 < bestScore3))) {
                  best3 = dest2;
                  bestScore3 = score3;
                }
              }
            }
            if ((best3 != (-1))) {
              dynamic tmp2 = labels[sp3];
              labels[sp3] = labels[best3];
              labels[best3] = tmp2;
              used2[sp3] = 1;
              used2[best3] = 1;
            }
          }
        }
      }
    }
    if ((config["chromaCleanupPasses"] > 0)) {
      dynamic chromaSingleton = (dynamic pixel) {
        dynamic sx = (pixel % width);
        dynamic sy = _mathfloor((pixel / width));
        dynamic current3 = labels[pixel];
        dynamic outsideSourceHue = ((preferred[pixel] & (1 << current3)) == 0);
        if ((((((((((((sx == 0) || (sy == 0)) || ((sx + 1) == width)) ||
                                        ((sy + 1) == height)) ||
                                    (sx < filmStrips["leftExclusive"])) ||
                                (sx >= filmStrips["rightBegin"])) ||
                            _truth(textProtect[pixel])) ||
                        _truth(deepBlack[pixel])) ||
                    (grad[pixel] >= config["sparkleEdge"])) ||
                (current3 < 2)) ||
            (!_truth(outsideSourceHue)))) {
          return false;
        }
        dynamic same3 = 0;
        for (dynamic dy10 = (-1); (dy10 <= 1); dy10++) {
          for (dynamic dx10 = (-1); (dx10 <= 1); dx10++) {
            if (((dx10 == 0) && (dy10 == 0))) continue;
            if ((labels[(((sy + dy10) * width) + (sx + dx10))] == current3))
              same3++;
          }
        }
        return (same3 <= config["chromaCleanupSame"]);
      };
      for (
        dynamic pass3 = 0;
        (pass3 < config["chromaCleanupPasses"]);
        pass3++
      ) {
        if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
        dynamic cleaned2 = _array("Uint8Array", labels);
        for (dynamic y8 = 1; ((y8 + 1) < height); y8++) {
          if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
          for (
            dynamic x8 = _mathmax(1, filmStrips["leftExclusive"]);
            ((x8 + 1) < filmStrips["rightBegin"]);
            x8++
          ) {
            dynamic sp4 = ((y8 * width) + x8);
            if ((!_truth(chromaSingleton(sp4)))) continue;
            dynamic radius2 = config["sparkleCleanupWindow"];
            dynamic srcTotal2 = <dynamic>[0, 0, 0];
            dynamic outTotal2 = <dynamic>[0, 0, 0];
            dynamic localCounts2 = <dynamic>[0, 0, 0, 0, 0, 0];
            dynamic count3 = 0;
            for (dynamic dy11 = (-radius2); (dy11 <= radius2); dy11++) {
              dynamic ny7 = (y8 + dy11);
              if (((ny7 < 0) || (ny7 >= height))) continue;
              for (dynamic dx11 = (-radius2); (dx11 <= radius2); dx11++) {
                dynamic nx7 = (x8 + dx11);
                if (((nx7 < filmStrips["leftExclusive"]) ||
                    (nx7 >= filmStrips["rightBegin"])))
                  continue;
                dynamic nb4 = ((ny7 * width) + nx7);
                srcTotal2[0] += baseL[nb4];
                srcTotal2[1] += baseA[nb4];
                srcTotal2[2] += baseB[nb4];
                dynamic pl2 = perceived[labels[nb4]];
                outTotal2[0] += pl2[0];
                outTotal2[1] += pl2[1];
                outTotal2[2] += pl2[2];
                localCounts2[labels[nb4]]++;
                count3++;
              }
            }
            dynamic sourceAverage2 = <dynamic>[
              (srcTotal2[0] / count3),
              (srcTotal2[1] / count3),
              (srcTotal2[2] / count3),
            ];
            dynamic outputAverage2 = <dynamic>[
              (outTotal2[0] / count3),
              (outTotal2[1] / count3),
              (outTotal2[2] / count3),
            ];
            dynamic beforeError2 = squaredDistance(
              sourceAverage2,
              outputAverage2,
            );
            dynamic current4 = labels[sp4];
            dynamic best4 = current4;
            dynamic bestScore4 =
                (beforeError2 +
                (0.002 *
                    squaredDistance(<dynamic>[
                      baseL[sp4],
                      baseA[sp4],
                      baseB[sp4],
                    ], perceived[current4])));
            for (dynamic candidate2 = 0; (candidate2 < 6); candidate2++) {
              if (((((candidate2 == current4) ||
                          (localCounts2[candidate2] == 0)) ||
                      ((preferred[sp4] & (1 << candidate2)) == 0)) ||
                  ((perceived[candidate2][0] - perceived[current4][0]) >
                      0.25))) {
                continue;
              }
              dynamic shifted2 = <dynamic>[
                (((outTotal2[0] - perceived[current4][0]) +
                        perceived[candidate2][0]) /
                    count3),
                (((outTotal2[1] - perceived[current4][1]) +
                        perceived[candidate2][1]) /
                    count3),
                (((outTotal2[2] - perceived[current4][2]) +
                        perceived[candidate2][2]) /
                    count3),
              ];
              dynamic afterError2 = squaredDistance(sourceAverage2, shifted2);
              dynamic directBefore2 = squaredDistance(<dynamic>[
                baseL[sp4],
                baseA[sp4],
                baseB[sp4],
              ], perceived[current4]);
              dynamic directAfter2 = squaredDistance(<dynamic>[
                baseL[sp4],
                baseA[sp4],
                baseB[sp4],
              ], perceived[candidate2]);
              dynamic score4 = (afterError2 + (0.002 * directAfter2));
              if ((((afterError2 <=
                          (beforeError2 + config["sparkleDataTolerance"])) &&
                      (directAfter2 <= (directBefore2 + 0.08))) &&
                  (score4 < bestScore4))) {
                best4 = candidate2;
                bestScore4 = score4;
              }
            }
            cleaned2[sp4] = best4;
          }
        }
        labels = cleaned2;
      }
    }
    return labels;
  }

  dynamic v7Config() {
    return <String, dynamic>{
      "bilateralRadius": 0,
      "bilateralSigmaSpatial": 1.35,
      "bilateralSigmaL": 0.05,
      "bilateralSigmaChroma": 0.06,
      "detailKeepFlat": 1,
      "edgeLow": 0.1,
      "edgeHigh": 0.3,
      "posterLLevels": 22,
      "posterCLevels": 10,
      "posterHBins": 36,
      "posterBlend": 0,
      "mergeColors": 0,
      "ditherL": 1,
      "ditherC": 1,
      "neutralChroma": 0.035,
      "deepBlackMargin": 0.07,
      "errorBarrierL": 10,
      "errorBarrierC": 10,
      "crossHuePenalty": 0.004,
      "regularizationLambda": 0,
      "regularizationEdge": 0.04,
      "regularizationSweeps": 0,
      "refinePasses": 1,
      "refineEdge": 0.025,
      "refineMinL": 0.7,
      "refineTolerance": 0,
      "refineSameNeighbors": 0,
      "leftTextOuterFraction": 0.6,
      "leftTextChroma": 0.075,
      "leftTextB": 0.035,
      "leftTextLMargin": 0.08,
      "leftTextEdgeScale": 6,
      "sparkleSweeps": 0,
      "sparkleRadius": 4,
      "sparkleEdge": 0.04,
      "sparkleBrightL": 0.7,
      "sparkleLumaDelta": 0.18,
      "sparkleSourceDelta": 0.05,
      "sparkleSourceDistance": 0.075,
      "sparkleDataTolerance": 0.001,
      "sparkleCleanupPasses": 0,
      "sparkleCleanupWindow": 1,
      "chromaCleanupPasses": 0,
      "chromaCleanupSame": 0,
      "chromaRelocateSweeps": 0,
      "chromaRelocateRadius": 4,
      "chromaRelocateEdge": 0.06,
      "chromaRelocateTolerance": 0,
      "reorderTile": 0,
      "reorderEdge": 0.03,
      "reorderPattern": 0.06,
      "dbsSweeps": 0,
      "dbsRadius": 2,
      "dbsSigma": 1,
      "dbsEdge": 0.06,
      "dbsDataWeight": 0.015,
      "dbsHueWeight": 0.002,
      "cleanupPasses": 0,
    };
  }

  dynamic v75Config() {
    dynamic c = v7Config();
    c["refineSameNeighbors"] = (-1);
    c["sparkleCleanupPasses"] = 1;
    c["chromaCleanupPasses"] = 1;
    return c;
  }

  dynamic perceivedToOklab() {
    dynamic arr = <dynamic>[];
    for (dynamic i = 0; (i < 6); i++) {
      dynamic p = PALETTE_PERCEIVED[i];
      _push(arr, rgbToOklab(p[0], p[1], p[2]));
    }
    return arr;
  }

  Future<dynamic> szEnhancedDither(dynamic imageData) async {
    dynamic width = imageData["width"];
    dynamic height = imageData["height"];
    dynamic n = (width * height);
    dynamic seedLabels = await v5SeedDither(imageData);
    onProgress?.call(0.15);
    checkCancelled?.call();
    dynamic tone = await balancedToneMap(imageData);
    onProgress?.call(0.3);
    checkCancelled?.call();
    tone["width"] = width;
    tone["height"] = height;
    dynamic lightness = tone["toneL"];
    dynamic grad = await sobelMagnitude(
      await boxBlur(lightness, width, height, 1),
      width,
      height,
    );
    onProgress?.call(0.4);
    checkCancelled?.call();
    dynamic perceived = perceivedToOklab();
    dynamic panelBlack = perceived[0][0];
    dynamic filmStrips = await detectFilmStrips(
      tone["toneL"],
      width,
      height,
      panelBlack,
    );
    onProgress?.call(0.45);
    checkCancelled?.call();
    dynamic v7Labels = await quantize(
      tone,
      grad,
      filmStrips,
      v7Config(),
      perceived,
      seedLabels,
    );
    onProgress?.call(0.65);
    checkCancelled?.call();
    dynamic v75Labels = await quantize(
      tone,
      grad,
      filmStrips,
      v75Config(),
      perceived,
      v7Labels,
    );
    onProgress?.call(0.85);
    checkCancelled?.call();
    dynamic out = _image(width, height);
    dynamic od = out["data"];
    for (dynamic o = 0; (o < n); o++) {
      if ((++_ticks & 31) == 0 && _shouldYield()) await _yield();
      dynamic rgbc = PALETTE_OUTPUT[v75Labels[o]];
      od[(o * 4)] = rgbc[0];
      od[((o * 4) + 1)] = rgbc[1];
      od[((o * 4) + 2)] = rgbc[2];
      od[((o * 4) + 3)] = 255;
    }
    return out;
  }
}
